### PR TITLE
minor change

### PR DESCRIPTION
**Pull request by ChaiBapchya**

### CODE REVIEW

**Comment by ChaiBapchya** [comment]
@mxnet-ci-bot run [centos-cpu, edge]

**Comment by ChaiBapchya** [comment]
@MXNet-CI-Bot run [centos-cpu]

**Comment by lanking520** [comment]
Jenkins CI successfully triggered.

**Comment by ChaiBapchya** [comment]
@mxnet-ci-bot random

**Comment by ChaiBapchya** [comment]
@MXNet-CI-Bot random

**Comment by lanking520** [comment]
Undefined action detected. 
Permissible actions are : run, trigger 
Example : @mxnet-ci-bot run [centos-cpu] 
Example : @mxnet-ci-bot trigger [centos-gpu]

**Comment by ChaiBapchya** [comment]
@mxnet-ci-bot rand

**Comment by lanking520** [comment]
Undefined action detected. 
Permissible actions are : run, trigger 
Example : @mxnet-ci-bot run [centos-cpu] 
Example : @mxnet-ci-bot trigger [centos-gpu]

**Comment by ChaiBapchya** [comment]
@mxnet-ci-bot run [clang]

**Comment by lanking520** [comment]
Jenkins CI successfully triggered.

**Comment by ChaiBapchya** [comment]
@MXNet-CI-Bot run [clang]

**Comment by lanking520** [comment]
Jenkins CI successfully triggered.

**Pull request closed without merging**
