### PR TITLE
change

### PR DESCRIPTION
**Pull request by ChaiBapchya**

### CODE REVIEW

**Comment by ChaiBapchya** [comment]
@mxnet-ci-bot run [clang]

**Comment by lanking520** [comment]
Jenkins CI successfully triggered.

**Comment by ChaiBapchya** [comment]
@mxnet-ci-bot run [edge]

**Comment by ChaiBapchya** [comment]
@MXNet-CI-Bot run [edge]

**Comment by ChaiBapchya** [comment]
@MXNet-CI-Bot run [edge]

**Comment by ChaiBapchya** [comment]
@MXNet-CI-Bot run [clang]

**Comment by lanking520** [comment]
Jenkins CI successfully triggered.

**Comment by ChaiBapchya** [comment]
@MXNet-CI-Bot run [clang]

**Comment by lanking520** [comment]
Jenkins CI successfully triggered.

**Comment by ChaiBapchya** [comment]
@MXNet-CI-Bot run [edge, centos-cpu]

**Comment by lanking520** [comment]
Jenkins CI successfully triggered.

**Comment by ChaiBapchya** [comment]
@MXNet-CI-Bot run [edge, centos-cpu, centos-gpu]

**Comment by lanking520** [comment]
Jenkins CI successfully triggered.

**Comment by ChaiBapchya** [comment]
@MXNet-CI-Bot run [edge, centos-cpu, centos-gpu]

**Comment by lanking520** [comment]
Jenkins CI successfully triggered.

**Comment by ChaiBapchya** [comment]
@MXNet-CI-Bot run [clang, centos-cpu, edge]

**Comment by lanking520** [comment]
Jenkins CI successfully triggered.

**Comment by ChaiBapchya** [comment]
@MXNet-CI-Bot run [all]

**Comment by lanking520** [comment]
Jenkins CI successfully triggered.

**Comment by ChaiBapchya** [comment]
@MXNet-CI-Bot tp

**Comment by lanking520** [comment]
Undefined action detected. 
Permissible actions are : run, trigger 
Example : @mxnet-ci-bot run [centos-cpu] 
Example : @mxnet-ci-bot trigger [centos-gpu]

**Comment by ChaiBapchya** [comment]
@MXNet-CI-Bot run [cent]

**Comment by lanking520** [comment]
None of the jobs entered are supported.

**Pull request closed without merging**
