### PR TITLE
Test 2dgpu PR on my own master

### PR DESCRIPTION
**Pull request by ChaiBapchya**
Changing the description to see what type of event is sent via Github webhook

### CODE REVIEW

**Comment by ChaiBapchya** [comment]
@mxnet-ci-bot test

**Comment by ChaiBapchya** [comment]
@MXNet-CI-Bot test

**Comment by ChaiBapchya** [comment]
@MXNet-CI-Bot t2

**Comment by ChaiBapchya** [comment]
here we go

**Comment by ChaiBapchya** [comment]
lets do this

**Comment by ChaiBapchya** [comment]
Julian

**Comment by ChaiBapchya** [comment]
Assange

**Comment by ChaiBapchya** [comment]
try

**Comment by ChaiBapchya** [comment]
u go

**Comment by ChaiBapchya** [comment]
ye lo on send_to_sqs trigger

**Comment by ChaiBapchya** [comment]
updated token with nice generator

**Comment by ChaiBapchya** [comment]
jonas

**Comment by ChaiBapchya** [comment]
joo

**Comment by ChaiBapchya** [comment]
lo

**Comment by antetokounmpogiannis** [comment]
yo

**Comment by antetokounmpogiannis** [comment]
imma try

**Comment by antetokounmpogiannis** [comment]
try

**Comment by antetokounmpogiannis** [comment]
@mxnet-ci-bot again

**Comment by ChaiBapchya** [comment]
Jenkins CI successfully triggered.

**Comment by antetokounmpogiannis** [comment]
yo from me

**Comment by antetokounmpogiannis** [comment]
yo

**Comment by antetokounmpogiannis** [comment]
@mxnet-ci-bot again

**Comment by ChaiBapchya** [comment]
Unauthorized access detected. 
Only following 3 categories can trigger CI : 
PR Author, MXNet Committer, Jenkins Admin.

**Comment by ChaiBapchya** [comment]
@mxnet-ci-bot run [centos-cpu]

**Comment by ChaiBapchya** [comment]
@MXNet-CI-Bot run [centos-cpu]

**Review by ChaiBapchya — COMMENTED** [review]
test_comment

**Pull request closed without merging**
