### PR TITLE
Minor change to readme

### PR DESCRIPTION
**Pull request by ChaiBapchya**

### CODE REVIEW

**Comment by ChaiBapchya** [comment]
@MXNet-CI-Bot random

**Comment by lanking520** [comment]
Undefined action detected. 
Permissible actions are : run, trigger 
Example : @mxnet-ci-bot run [centos-cpu] 
Example : @mxnet-ci-bot trigger [centos-gpu]

**Comment by ChaiBapchya** [comment]
@MXNet-CI-Bot run [clang]

**Comment by ChaiBapchya** [comment]
@MXNet-CI-Bot run [all]

**Comment by ddavydenko** [comment]
@MXNet-CI-Bot run [all]

**Comment by lanking520** [comment]
Unauthorized access detected. 
Only following 3 categories can trigger CI : 
PR Author, MXNet Committer, Jenkins Admin.

**Comment by josephevans** [comment]
@MXNet-CI-Bot run [centos-cpu]

**Comment by lanking520** [comment]
Unauthorized access detected. 
Only following 3 categories can trigger CI : 
PR Author, MXNet Committer, Jenkins Admin.

**Comment by ChaiBapchya** [comment]
@mxnet-ci-bot run [centos-cpu]

**Comment by ChaiBapchya** [comment]
@MXNet-CI-Bot run [centos-cpu, centos-gpu]

**Pull request closed without merging**
